import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Download, Mail, MapPin, ShieldCheck } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { Navbar } from "@/components/navbar";
import { ProjectCard } from "@/components/project-card";
import { ExternalAnchor, SectionHeading, TagList } from "@/components/ui";
import { education } from "@/data/education";
import { experiences } from "@/data/experience";
import { about, profile } from "@/data/profile";
import { projects } from "@/data/projects";
import { skillGroups } from "@/data/skills";
import { socialLinks } from "@/data/social-links";

export default function Home() {
  const personJson = { "@context": "https://schema.org", "@type": "Person", name: profile.name, email: profile.email, image: profile.portrait, homeLocation: { "@type": "Place", name: profile.basedIn }, url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://raflyathallah.vercel.app", sameAs: socialLinks.filter((link) => link.label !== "Email").map((link) => link.href), alumniOf: { "@type": "CollegeOrUniversity", name: education.institution }, knowsAbout: skillGroups.flatMap((group) => group.skills) };
  return <>
    <a className="skip-link" href="#main">Skip to content</a><Navbar />
    <main id="main">
      <section id="home" className="hero"><div className="network-grid" /><div className="hero-copy"><span className="status"><i />Computer Science Student · Network Security</span><p className="kicker">Hi, I’m</p><h1>Rafly Athallah<br /><span>Khansa Putra.</span></h1><h2>{profile.title}</h2><p className="hero-summary">{profile.summary}</p><div className="hero-actions"><a className="button primary" href="#projects">View my projects <ArrowRight /></a><Link className="button secondary" href={profile.cvPath} download="Rafly-Athallah-CV-2026.pdf">Download CV <Download /></Link><a className="button ghost" href="#contact">Contact me</a></div><div className="hero-socials">{socialLinks.map((link) => <ExternalAnchor key={link.label} {...link} />)}</div></div><div className="portrait-wrap"><div className="portrait-frame"><Image src={profile.portrait} alt="Portrait of Rafly Athallah Khansa Putra wearing a black suit" fill priority sizes="(max-width: 800px) 80vw, 36vw" /></div><div className="portrait-note"><ShieldCheck /><span>Focused on building<br /><b>secure, useful systems.</b></span></div></div><a href="#about" className="scroll-cue">Explore <ArrowDown /></a></section>
      <section id="about" className="section split"><div><SectionHeading eyebrow="01 / About" title="Security-minded. User-centered. Curious by design." /><div className="about-copy">{about.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><aside className="principles"><p className="mono">WORKING PRINCIPLES</p>{[["01", "Secure by intention"], ["02", "Research before assumptions"], ["03", "Clarity over complexity"]].map((item) => <div key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3></div>)}</aside></section>
      <section id="expertise" className="section"><SectionHeading eyebrow="02 / Expertise" title="A multidisciplinary technical toolkit." description="Security is the foundation, supported by software engineering, applied AI, and interaction design." /><div className="skill-grid">{skillGroups.map((group, index) => <article className="skill-card" key={group.title}><span className="skill-index">0{index + 1}</span><h3>{group.title}</h3><p>{group.description}</p><TagList items={group.skills} /></article>)}</div></section>
      <section id="experience" className="section"><SectionHeading eyebrow="03 / Experience" title="Applying security thinking in practice." />{experiences.map((experience) => <article className="experience" key={experience.company}><div className="experience-media"><div className="experience-date">{experience.period}</div><Image className="organization-logo experience-logo" src={experience.logo} alt="PT Asuransi BRI Life logo" width={230} height={104} sizes="(max-width: 700px) 180px, 230px" /></div><div><span className="status compact"><i />{experience.focus}</span><h3>{experience.role}</h3><h4>{experience.company}</h4><ul>{experience.responsibilities.map((responsibility) => <li key={responsibility}>{responsibility}</li>)}</ul><p className="confidentiality"><ShieldCheck /> Work shown at a responsible level—no confidential systems or findings disclosed.</p></div></article>)}</section>
      <section id="projects" className="section"><SectionHeading eyebrow="04 / Selected work" title="Projects across technology and impact." description="Research, prototypes, and working systems shaped by real user and societal needs." /><div className="projects-grid">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} index={index} />)}</div></section>
      <section id="education" className="section"><SectionHeading eyebrow="05 / Education" title="Building a strong technical foundation." /><article className="education-card"><div className="education-logo-wrap"><Image className="organization-logo education-logo" src={education.logo} alt="BINUS University logo" width={180} height={110} sizes="(max-width: 700px) 150px, 180px" /></div><div><p className="mono">{education.period}</p><h3>{education.institution}</h3><h4>{education.degree}</h4><p>{education.specialization} · {education.location}</p></div><strong>{education.completion}</strong></article></section>
      <section id="contact" className="section contact"><div><SectionHeading eyebrow="06 / Contact" title="Let’s build something meaningful." description="For opportunities, project discussions, or professional connections, send a message or reach out directly." /><div className="contact-details"><a href={`mailto:${profile.email}`}><Mail /><span>Email<b>{profile.email}</b></span></a><div><MapPin /><span>Based in<b>{profile.basedIn}</b></span></div></div></div><ContactForm /></section>
    </main>
    <footer><div><p><b>{profile.siteName}</b><br />Security-minded technology developer.</p></div><div>{socialLinks.map((link) => <ExternalAnchor key={link.label} {...link} />)}</div><p>© {new Date().getFullYear()} {profile.name}</p><a href="#home" className="back-top">Back to top ↑</a></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personJson) }} />
  </>;
}
